package TeamManagementSystem;

import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Scanner;

import com.mysql.jdbc.ResultSet;

public class Report {
	int choice;
	Connection con=null;
	PreparedStatement ps=null;
	ResultSet rs=null;
	String URL="jdbc:mysql://localhost:3306/task_system";
	StringBuffer report=new StringBuffer();
	Scanner in=new Scanner(System.in);
	public Report(int id,String reportFor,String type) throws IOException
	{
			generateReport(id,reportFor,type);
		
	}
	private void generateReport(int id, String reportFor, String type) throws IOException {
		report.append("Generated By:"+id+"\nReport For:"+reportFor+"\tReport Type:"+type);
		Task task=new Task();
	   report.append(task.getTaskReport(id,type,reportFor));
	   System.out.println(report.toString()+"\n Do you want to upload report to a file:\n1.Yes\n2.No");
	choice=in.nextInt();
	if(choice==1)
	{
		uploadReport(report.toString(),id+"_"+reportFor+"_"+type+"_");
	}
	}
	private void uploadReport(String report,String fileName) throws IOException {
		String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date());
		try (PrintStream out = new PrintStream(new FileOutputStream(fileName+timeStamp+".txt"))){
 		   new FileWriter(fileName+timeStamp+".txt").close();
 	   out.write(report.getBytes());
 	   System.out.println("Report Uploaded");
 	   }
	}
	}


